export const rounds = {
  1: [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  ],
  2: [
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x                                x",
    "x                                x",
    "x                                x",
    "x      xx                        x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x                  xx            x",
    "x                                x",
    "x                                x",
    "x                                x",
    "x         x                      x",
    "x                                x",
    "x                                x",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  ],
};
